### ISSUE TITLE
Refactor `Histogram` class

### ISSUE THREAD

**Issue by stwunsch** [KIT-CMS/ntuple_processor#23]
https://github.com/KIT-CMS/ntuple_processor/blob/master/utils/_booking.py#L254

- Please introduce a `Binning` object, that can be reused.
- The should be only one way to book a `Histogram`, please remove the conditional setup in the ctor.
- Just use bin edges for the binning, no other mode is required (like the typical nbins, lower, upper mode in ROOT)
- The binning needs a name so that we can build a proper tag for the histogram in the file.

**Comment by maxgalli** [comment]
Addressed in https://github.com/KIT-CMS/ntuple_processor/pull/31 and https://github.com/KIT-CMS/ntuple_config/pull/6. 

Despite what we said in the last call, I thought that having only the name of the original selections in the name of Units is enough, since we change 'Nominal' with the name of the variations. This means e.g. that if we apply the variation ```CMS_eff_trigger_mt_Run2017Down``` to:
```DY#mt-DY-ZJ#m_vis#Nominal#m_vis```
we get:
```DY#mt-DY-ZJ#CMS_eff_trigger_mt_Run2017Down#m_vis```
and not:
```DY#mt-DY-ZJ-trg_mt_eff_weight#CMS_eff_trigger_mt_Run2017Down#m_vis```

**Comment by stwunsch** [comment]
I keep this open for now and check whether something breaks / gets complicated.
