### ISSUE TITLE
GraphManager default arguments

### ISSUE THREAD

**Issue by stwunsch** [KIT-CMS/ntuple_processor#33]
Should the `GraphManager` split selections by default? What is the impact of doing so?

**Comment by maxgalli** [comment]
In terms of performance basically nothing as we have seen from the benchmarking.
From the "practical" point of view the consequences are the following:
- if we DON'T split, when we apply a variation such as AddWeight or ReplaceWeight, this will produce another Selection with the same name but with a different/one more Weight; for this reason, when we go into the "merge_selections" part, the two above mentioned selections will not be merged (because even if most of the cuts/weights are the same, there is one element that does not match);
- the previous point has an effect also in the pretty-printing (not particularly important, but still worth mentioning): if we split, the pretty-printing that I implemented becomes super long and usually does not fit the terminal window, but it's still clear; when we don't split, in the common cases the pretty-printing is super nice (even if as I said, if you apply one of the above mentioned types of variation you will have two selection-nodes with the same name but internally a different element); that's the reason why I was thinking to implement the pretty-printing with ```asciitree``` for the split case, in order to avoid the not-fitting the terminal window problem; the package is not big and I can easily include it in order to avoid dependencies, I remember that I already looked into it and it should be more or less straightforward.

**Comment by stwunsch** [comment]
ok, so we keep it on false as default, seems fine by me.
